<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Third Party Services
    |--------------------------------------------------------------------------
    |
    | Credentials and configuration for external services belong here so
    | application code does not access environment variables directly.
    |
    */

    'postmark' => [
        'key' => env('POSTMARK_API_KEY'),
    ],

    'resend' => [
        'key' => env('RESEND_API_KEY'),
    ],

    'ses' => [
        'key' => env('AWS_ACCESS_KEY_ID'),
        'secret' => env('AWS_SECRET_ACCESS_KEY'),
        'region' => env('AWS_DEFAULT_REGION', 'us-east-1'),
    ],

    'slack' => [
        'notifications' => [
            'bot_user_oauth_token' => env('SLACK_BOT_USER_OAUTH_TOKEN'),
            'channel' => env('SLACK_BOT_USER_DEFAULT_CHANNEL'),
        ],
    ],
    /*
    |--------------------------------------------------------------------------
    | IPROG SMS
    |--------------------------------------------------------------------------
    |
    | IPROG SMS delivers verification codes generated by Rincomm.
    | The API token must remain in the environment and must never be committed.
    |
    */

    'iprog_sms' => [
        'base_url' => env(
            'IPROG_SMS_BASE_URL',
            'https://www.iprogsms.com'
        ),

        'api_token' => env('IPROG_SMS_API_TOKEN'),

        'timeout' => (int) env(
            'IPROG_SMS_TIMEOUT',
            10
        ),
    ],
];
